import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from './Home'
import Header from './layouts/Header'

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>MyTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header/>
        <div className="content">
          <HomePage/>
        </div>
      </main>
    </div>
  )
}

export default Home
